### ISSUE TITLE
Doesn't compile under Linux Mint (64-bit)

### ISSUE THREAD

**Issue by scumola** [sth/ups#1]
I used to use this debugger eons ago (like 1995-ish) and I used to love it.  I found your repo and I decided to try compiling it and getting it to run, but alas, I don't think that it's built for 64-bit compilers/OS.  Issues with LONGLONG_xxx defines keep it from building.

Would be great to see this running again.  I'd love to use it, but I'm afraid that it might be more effort than it's worth.

**Comment by sth** [comment]
Adding `--enable-longlong` might help. This is the `configure` line I would recommend:

    ./configure --enable-dwarf --enable-elf --enable-longlong

I haven't tested it on Mint, but on Ubunutu that works without `LONGLONG_*` issues. It would make sense to make that option the default, but I'm not too keen on touching the autoconf stuff...

I have changed the `README.md` accordingly and also pushed a bunch of patches that were not on Github yet.

**Comment by scumola** [comment]
Ok, next error:

```
In file included from ./xc_builtins.c:144:
./cx_libvars.h:80:11: error: ‘_IO_2_1_stdin_’ undeclared here (not in a function)
   80 |         V(_IO_2_1_stdin_)
      |           ^~~~~~~~~~~~~~
./cx_libvars.h:36:42: note: in definition of macro ‘V’
   36 | #       define V(var)           (char *)&var,
      |                                          ^~~
./cx_libvars.h:81:11: error: ‘_IO_2_1_stdout_’ undeclared here (not in a function)
   81 |         V(_IO_2_1_stdout_)
      |           ^~~~~~~~~~~~~~~
./cx_libvars.h:36:42: note: in definition of macro ‘V’
   36 | #       define V(var)           (char *)&var,
      |                                          ^~~
./cx_libvars.h:82:11: error: ‘_IO_2_1_stderr_’ undeclared here (not in a function)
   82 |         V(_IO_2_1_stderr_)
      |           ^~~~~~~~~~~~~~~

```

**Comment by scumola** [comment]
Ok, I got it to build and it'll open a static executable, but building with -gdwarf kills it.

```
steve@steve-Latitude-7420:~/Documents/ups/ups/tests$ gcc -static -gdwarf -o blah blah.c
steve@steve-Latitude-7420:~/Documents/ups/ups/tests$ ../ups/ups blah
Can't find shared library information in ELF executable blah (no `.dynamic' section)
DWARF error : attribute form not string - OK (DIE blah.c <12><12>)
DWARF error : attribute form not string - OK (DIE blah.c <12><12>)
Fatal error: segmentation fault.
Dumping core ... Segmentation fault (core dumped)
steve@steve-Latitude-7420:~/Documents/ups/ups/tests$ gcc -static -o blah blah.c
steve@steve-Latitude-7420:~/Documents/ups/ups/tests$ ../ups/ups blah
Can't find shared library information in ELF executable blah (no `.dynamic' section)
steve@steve-Latitude-7420:~/Documents/ups/ups/tests$ cat blah.c
#include <stdio.h>
int main(void) {
	printf("Hello world\n");
}
steve@steve-Latitude-7420:~/Documents/ups/ups/tests$ 

```

**Comment by sth** [comment]
New recommended compilation options:
```
gcc -gdwarf -no-pie -o blah blah.c
```
Static linking seems to be problematic (#2) and position independent programs aren't recognized properly, so `-no-pie` is necessary (#3).

Additionally a small patch was needed to support a new Dwarf feature used by gcc 11.

**Comment by scumola** [comment]
Sorry for the back-and-forth, but that doesn't seem to work for me either.

```
steve@steve-Latitude-7420:~/Documents/ups/ups/tests$ cat blah.c
#include <stdio.h>
int main(void) {
	printf("Hello world\n");
}
steve@steve-Latitude-7420:~/Documents/ups/ups/tests$ gcc -gdwarf -no-pie -o blah blah.c
steve@steve-Latitude-7420:~/Documents/ups/ups/tests$ ups blah
Fatal error: segmentation fault.
Dumping core ... Segmentation fault (core dumped)
steve@steve-Latitude-7420:~/Documents/ups/ups/tests$ 
```

**Comment by scumola** [comment]
Using the latest build, I can now get in and debug something!  Thanks so much!  It's like a blast from the past!  Really helpful!  :)

**Comment by sth** [comment]
Nice! Have fun with it!

In case you run into more segmentation faults/... and want to investigate those, debugging ups in gdb works fairly well in my experience:

    gdb --args ups blah

And definitely feel free to ask me if any new problems/... arise :)
